export const mockData = [
  {
    id: '2809a045-b669-41e4-94be-08fcde9de72f',
    name: 'Monica Grant',
    description: '',
    age: '32',
    bloodType: 'A+',
    tags: ['Educ', 'Cook', 'Eng'],
    infected: true,
    injured: true,
    canWork: true,
  },
  {
    id: 'a99c2c5d-d228-49fa-ba93-75aec37b2ef5',
    name: 'Christina Hansen',
    description: '',
    age: '25',
    bloodType: 'B+',
    tags: ['Sec', 'Eng', 'HC'],
    infected: true,
    injured: true,
    canWork: true,
  },
  {
    id: '6afadf3a-3406-43b0-b0c6-82e830132e31',
    name: 'Andrew Ahmed',
    description: '',
    age: '34',
    bloodType: 'O+',
    tags: ['Eng', 'Crafts', 'Educ'],
    infected: true,
    injured: true,
    canWork: false,
  },
  {
    id: 'a47fbf79-18c3-49bd-bc04-87780058c3d8',
    name: 'Max Parkes',
    description: '',
    age: '45',
    bloodType: 'AB+',
    tags: ['Crafts', 'HC', 'Cook'],
    infected: false,
    injured: false,
    canWork: true,
  },
  {
    id: 'acb84c8d-0b15-448f-be96-1d5f451d1cc8',
    name: 'Kieran Campbell',
    description: '',
    age: '15',
    bloodType: 'B−',
    tags: ['HC', 'Sec', 'Educ'],
    infected: true,
    injured: true,
    canWork: false,
  },
  {
    id: 'f86b4fee-4dd7-4e91-aac4-ec8d52b242e5',
    name: 'Amelia Osborne',
    description: '',
    age: 0,
    bloodType: 'O+',
    tags: ['HC', 'Crafts', 'Cook'],
    infected: false,
    injured: true,
    canWork: true,
  },
];
